
spring.application.name: miya-search-service

server:
  port: 8811
  tomcat:
    uri-encoding: UTF-8

#向服务中心注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://www.miya.com:8888/eureka/


spring.datasource:
  continue-on-error: false
  initialize: false
  jmx-enabled: false
  name: dataSource
  type: 'com.zaxxer.hikari.HikariDataSource'
  driver-class-name: 'com.mysql.jdbc.Driver'
  url: 'jdbc:mysql://www.miya.com:3306/miyadb?useUnicode=true&characterEncoding=utf-8&useSSL=true'
  username: root
  password: root


spring.data:
    solr:
      host: 'http://120.78.222.191:8983/solr/mycore'




####### Kafka配置  #########

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 120.78.222.191:9092
          zk-nodes: 120.78.222.191:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: true
      bindings:
        input:
          destination: item-add-topic
          group: miya-group
          consumer:
            concurrency: 1
            partitioned: false


spring.application.index: 0

spring.cloud.stream.instanceCount: 1
spring.cloud.stream.instanceIndex: 0

####### Kafka配置  #########

---
spring:
  profiles: envProd

---
spring:
  profiles: envTest

---
spring:
  profiles: envDev