spring.application.name: miya-portal-web

server:
  port: 8800

#向服务中心注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://120.78.222.191:8888/eureka

spring:
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp



##首页大广告位
#内容分类id
AD1_CATEGORY_ID: 89
AD1_WIDTH: 670     #宽屏
AD1_WIDTH_B: 550   #窄屏
AD1_HEIGHT: 240
AD1_HEIGHT_B: 240


---
spring:
  profiles: envProd

---
spring:
  profiles: envTest

---
spring:
  profiles: envDev

