
spring.application.name: miya-content-service

server:
  port: 8821

#向服务中心注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://www.miya.com:8888/eureka/


spring.datasource:
  continue-on-error: false
  initialize: false
  jmx-enabled: false
  name: dataSource
  type: 'com.zaxxer.hikari.HikariDataSource'
  driver-class-name: 'com.mysql.jdbc.Driver'
  url: 'jdbc:mysql://www.miya.com:3306/miyadb?useUnicode=true&characterEncoding=utf-8&useSSL=true'
  username: root
  password: root


#图片服务的url
IMAGE_SERVER_URL: http://120.78.222.191/


#redis中缓存首页内容的key
INDEX_CONTENT: INDEX_CONTENT

# Redis数据库索引（默认为0）
spring.redis:
  database: 0
  host: www.miya.com
  port: 6379
  password: chen0813
  pool.max-active: 8
  pool.max-wait: -1
  pool.max-idle: 8
  pool.min-idle: 0
  timeout: 0


---
spring:
  profiles: envProd

---
spring:
  profiles: envTest

---
spring:
  profiles: envDev






